module: iASL
author: Temple University Capstone Students Liam Miller, Ian Applebaum, Likhon Gomes
github_url: https://github.com/Capstone-Projects-2020-Spring/iASL-iOS
exclude:
#   - "**/*-ObjC.swift"
#   - "**/*Deprecations.swift"
#   - "Source/Siesta/Support/Siesta-ObjC.swift"     # until Cocoadocs gets https://github.com/realm/jazzy/pull/640
#   - "Source/SiestaUI/SiestaUI-ObjC.swift"         # ditto
#   - "Source/Siesta/Support/Ω_Deprecations.swift"  # ditto

# copyright: '© 2018 [Bust Out Solutions](http://bustoutsolutions.com) under [open source license](https://github.com/bustoutsolutions/siesta/blob/master/LICENSE).'

# swift_version: 4.2.0

theme: jony
min_acl: private
docset_icon: /Users/ianapplebaum/Documents/github/iASL-iOS/ImageClassification/Assets.xcassets/AppIcon.appiconset/1024.png

# custom_categories:
#   - name: Resources
#     children:
#     - Service
#     - Resource
#     - Entity
#     - Configuration
#     - ConfigurationPatternConvertible
#     - TypedContentAccessors

#   - name: Observing Resources
#     children:
#     - ResourceObserver
#     - ResourceObserverClosure
#     - ResourceEvent

#   - name: Requests
#     children:
#     - Request
#     - RequestMethod
#     - RequestState
#     - RequestError
#     - Response
#     - ResponseInfo

#   - name: Request Customization
#     children:
#     - RequestChainAction
#     - RequestDelegate
#     - RequestCompletionHandler

#   - name: Response Pipeline
#     children:
#     - Pipeline
#     - PipelineStage
#     - PipelineStageKey
#     - ResponseTransformer
#     - ResponseContentTransformer
#     - StandardTransformer
#     - JSONResponseTransformer(_:)
#     - TextResponseTransformer(_:)
#     - ImageResponseTransformer(_:)

#   - name: Logging
#     children:
#     - SiestaLog

#   - name: Caching
#     children:
#     - EntityCache

#   - name: UI Helpers
#     children:
#     - ResourceStatusOverlay
#     - RemoteImageView

#   - name: Network Layer
#     children:
#     - NetworkingProvider
#     - NetworkingProviderConvertible
#     - RequestNetworking
#     - RequestNetworkingCompletionCallback
#     - RequestTransferMetrics
#     - URLSessionProvider
github_file_prefix: https://github.com/Capstone-Projects-2020-Spring/iASL-iOS/tree/9458403eb8f9397c2b9b584241fbfe0bdf1411a0
