on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
name: "Integration Testing"

jobs:
  test:
    name: Integration Test
    runs-on: macos-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.3,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
         pod install
         ./RunScripts/download_models.sh
          xcodebuild clean test -workspace ImageClassification.xcworkspace -scheme ImageClassification -destination "${destination}" -enableCodeCoverage YES CODE_SIGNING_ALLOWED=NO ONLY_ACTIVE_ARCH=NO
          DERIVED_DATA_PATH=`xcodebuild -workspace "ImageClassification.xcworkspace" -scheme "ImageClassification" -showBuildSettings | grep OBJROOT | cut -d "=" -f 2 - | sed 's/^ *//'`
          DERIVED_DATA_PATH=`dirname "$DERIVED_DATA_PATH"`
          DERIVED_DATA_PATH=`dirname "$DERIVED_DATA_PATH"`
        env:
         destination: ${{ matrix.destination }}
      - name: Archive Failed Tests artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: FailureDiff
          path: $DERIVED_DATA_PATH/Logs/Test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODE_COV }} # not required for public repos
          flags: ImageClassification
#   add_permalink:
#     runs-on: [ubuntu-latest]
#     steps:
#       - uses: actions/checkout@v2
#         with:
#             ref: ${{ github.head_ref }}
#       - run: |
#           echo $PATH
#           sed '$d' .jazzy.yaml > temp
#           cat temp > .jazzy.yaml
#           rm temp
#           echo "github_file_prefix: https://github.com/Capstone-Projects-2020-Spring/iASL-iOS/tree/${{ github.sha }}" >> .jazzy.yaml
#       - uses: stefanzweifel/git-auto-commit-action@v4.1.1
#         with:
#           commit_message: Apply jazzy config changes
#           branch: ${{ github.head_ref }}
#           commit_user_name: ApplebaumIan
#           commit_user_email: ian.tyler@electricbluefish.com
#           commit_author: Ian Applebaum <ian.tyler@electricbluefish.com>
#           commit_options: ''
#           token: ${{ secrets.KEY_TOKEN }}
