name: Setup Jazzy Config
on: [pull_request]
jobs:
   add_permalink:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo $PATH
          sed '$d' .jazzy.yaml > temp
          cat temp > .jazzy.yaml
          rm temp
          echo "github_file_prefix: https://github.com/Capstone-Projects-2020-Spring/iASL-iOS/tree/${{ github.sha }}" >> .jazzy.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: Apply jazzy config changes
          branch: ${GITHUB_REF:11}
          commit_user_name: ApplebaumIan
          commit_user_email: ian.tyler@electricbluefish.com
          commit_author: Ian Applebaum <ian.tyler@electricbluefish.com>
          commit_options: ''
          token: ${{ secrets.KEY_TOKEN }}
